name: health_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  provider: ^6.1.5
  go_router: ^15.1.2
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.5.3
  lottie: ^3.3.1
  http: ^1.4.0
  intl: ^0.20.2
  openai_dart: ^0.4.5
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.6.0+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/heartbeat.png
    - assets/images/health_logo.png
    - assets/animations/health.json
    - assets/animations/progress.json
    - assets/animations/motivation.json
    - .env

